export const enum NotifTag {
  // microprocess actions
  TASK_STARTED = 'TASK_STARTED',
  TASK_EXECUTED = 'TASK_EXECUTED',
  TASK_SUBMITTED = 'TASK_SUBMITTED',
  TASK_COMPLETED = 'TASK_COMPLETED',
  TASK_CANCELED = 'TASK_CANCELED',
  TASK_ON_PAUSE = 'TASK_ON_PAUSE',
  TASK_VALID = 'TASK_VALID',
  TASK_LOG_CREATED = 'TASK_LOG_CREATED',
  TASK_LOG_UPDATED = 'TASK_LOG_UPDATED',
  TASK_ITEM_TO_CHECK = 'TASK_ITEM_TO_CHECK',
  TASK_ITEM_CHECKED = 'TASK_ITEM_CHECKED',
  TASK_ITEM_UNCHECKED = 'TASK_ITEM_UNCHECKED',

  // query manager actions
  Q_CREATED = 'Q_CREATED',
  Q_INSANCE_CREATED = 'Q_INSANCE_CREATED',
  Q_INSTANCE_VALIDATED = 'Q_INSTANCE_VALIDATED',
  Q_INSTANCE_TO_VALIDE = 'Q_INSTANCE_TO_VALIDE',
  Q_INSTANCE_TO_POST_VALIDATE = 'Q_INSTANCE_TO_POST_VALIDATE',
  Q_INSTANCE_REJECTED = 'Q_INSTANCE_REJECTED',

  // Audit actions
  AUDIT_STARTED = 'AUDIT_STARTED',
  AUDIT_EXECUTED = 'AUDIT_EXECUTED',
  AUDIT_SUBMITTED = 'AUDIT_SUBMITTED',
  AUDIT_COMPLETED = 'AUDIT_COMPLETED',
  AUDIT_CANCELED = 'AUDIT_CANCELED',
  AUDIT_ON_PAUSE = 'AUDIT_ON_PAUSE',
  AUDIT_INITILIZED = 'AUDIT_INITILIZED',

  // recommandation actions
  RECOM_STARTED = 'RECOM_STARTED',
  RECOM_EXECUTED = 'RECOM_EXECUTED',
  RECOM_SUBMITTED = 'RECOM_SUBMITTED',
  RECOM_COMPLETED = 'RECOM_COMPLETED',
  RECOM_CANCELED = 'RECOM_CANCELED',
  RECOM_ON_PAUSE = 'RECOM_ON_PAUSE',
  RECOM_INITILIZED = 'RECOM_INITILIZED',

  // microproject actions
  PRJ_TASK_STARTED = 'PRJ_TASK_STARTED',
  PRJ_TASK_EXECUTED = 'PRJ_TASK_EXECUTED',
  PRJ_TASK_SUBMITTED = 'PRJ_TASK_SUBMITTED',
  PRJ_TASK_COMPLETED = 'PRJ_TASK_COMPLETED',
  PRJ_TASK_CANCELED = 'PRJ_TASK_CANCELED',
  PRJ_TASK_ON_PAUSE = 'PRJ_TASK_ON_PAUSE',
  PRJ_TASK_VALID = 'PRJ_TASK_VALID',
  PRJ_TASK_ITEM_TO_CHECK = 'PRJ_TASK_ITEM_TO_CHECK',
  PRJ_TASK_ITEM_CHECKED = 'PRJ_TASK_ITEM_CHECKED',
  PRJ_TASK_LOG_CREATED = 'PRJ_TASK_LOG_CREATED',
  PRJ_TASK_LOG_UPDATED = 'PRJ_TASK_LOG_UPDATED',
}
