export const enum ProcessEventRecurrence {
  ONCE = 'ONCE',

  ALLAWAYS = 'ALLAWAYS',

  WEEK = 'WEEK',

  EVERY_WEEK_ON_DAY = 'EVERY_WEEK_ON_DAY',

  EVERY_YEAR_ON_DATE = 'EVERY_YEAR_ON_DATE',

  EVERY_MONTH = 'EVERY_MONTH',

  EVERY_MONTH_OF_DAY_POSITION = 'EVERY_MONTH_OF_DAY_POSITION',
}
