export enum ProjectDeleteMode {
  DELETE_WITH_CHILDREN = 'DELETE_WITH_CHILDREN',
  DELETE_AND_ASSOCIATE_FIRST_PREVIEW_PARENT_TO_CHILDREN = 'DELETE_AND_ASSOCIATE_FIRST_PREVIEW_PARENT_TO_CHILDREN',
  DELETE_AND_LEAVE_CHILDREN_ORPHANED = 'DELETE_AND_LEAVE_CHILDREN_ORPHANED',
}
